GET http://localhost:3003/api/currency

GET http://localhost:3003/api/country

GET http://localhost:3003/api/currency-countryName

###

POST http://localhost:3003/api/country
Content-Type: application/json

{
  "name": "United States"
}

{
  "name": "Canada"
}


POST http://localhost:3003/api/currency
Content-Type: application/json

{
  "currencyCode": "USD", 
  "conversionRate": 1.0, 
  "countryId": 1
}

{
  "currencyCode": "CAD",
  "conversionRate": 1.0,
  "countryId": 2
}


###
PUT http://localhost:3003/api/currency/1/0.8

###
DELETE http://localhost:3003/api/currency/2

DELETE http://localhost:3003/api/country/1